sudo: required

language: python

services:
  - docker

before_script:
  - python --version
  - docker version
  - docker ps -a
  - docker build -t ub-es:x .
  - docker images
  - docker ps -a

script:
  - docker run -it -P ub-es:x sh -c 'tightvncserver :10000; sleep 10s'

