#!/bin/sh -xe

echo 'deb http://archive.ubuntu.com/ubuntu/ xenial-security multiverse' >> /etc/apt/sources.list
echo 'deb-src http://archive.ubuntu.com/ubuntu/ xenial-security multiverse' >> /etc/apt/sources.list

apt-get update 

apt-get install -y m2crypto vim mtr vnstat curl wget

apt-get install -y lxde-core lxterminal tightvncserver xrdp proxychains cpulimit flashplugin-nonfree

dpkg -i /data/google-chrome*.deb

# xvnc server porst, if $DISPLAY=:1 port will be 5901	
EXPOSE 15900

apt-get clean
apt-get autoclean
apt-get remove -y
rm -rf /var/lib/apt/lists/*
rm -rf /tmp/*
rm -rf /data/google-chrome*.deb

chmod +x /data/run-in-docker
ln -s /data/run-in-docker /run-in-docker

