#!/bin/sh

start_services()
{
	sh -c 'sleep 11m; killall firefox;' &

	# SS_ARGS='-k *** -m *** -p *** -s ***'
	#/data/shadowsocks-local -b 127.0.0.1 -l 1080 $SS_ARGS &
}

rm -rf /root/.vnc/*.log /tmp/.X10000-lock /tmp/.X11-unix/X10000 

export USER=root 

tightvncserver :10000 

export DISPLAY=localhost:10000.0

start_services


firefox	http://www.ebesucher.com/surfbar/clarencep 

	# --proxy-server="socks5://127.0.0.1:1080" \
	# --host-resolver-rules="MAP * 0.0.0.0 , EXCLUDE localhost" \

